POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jack London",
    "number": "6379-873293"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tom Saul"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "6379-873293"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "247-794-4827"
}